management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /monitoring
  info:
    git:
      mode: full
  endpoint:
    health:
      show-details: always
springdoc:
  swagger-ui:
    csrf:
      enabled: 'true'
spring:
  flyway:
    baseline-on-migrate: 'true'
    locations: classpath:db/migration
    encoding: UTF-8
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    placeholder-replacement: 'false'
  data:
    redis:
      active: 'false'
    stream:
      detection: objectdetector
      aggregator: aggregator
      positionsource: positionsource
    rest:
      detection-strategy: annotated
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration,org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      naming:
        physical-strategy: de.starwit.persistence.config.DatabasePhysicalNamingStrategy
  datasource:
    hikari:
      connection-timeout: '10000'
    password: urbalytix
    username: urbalytix
    url: jdbc:postgresql://localhost:5432/urbalytix
  profiles:
    active: dev
  banner:
    location: classpath:banner.txt
rest:
  base-path: /api
server:
  port: '8081'
  compression:
    enabled: 'true'
  servlet:
    context-path: /urbalytix
infra:
  trash:
    endpoint: https://hostname
    secret: secret

landing:
  endpoints:
    - name: "wastemanagement"
      endpoint: "#/status"
      image: "waste-management.jpg"
      order: 1
    - name: "parking"
      endpoint: "https://dashboard.staging.data-wolfsburg.de/d/beaxyf615u29sa/ueberblick-meckauer-weg?orgId=1&refresh=5s"
      image: "parking.jpg"
      order: 2
    - name: "trafficlive"
      endpoint: "https://visualizer.staging.data-wolfsburg.de/"
      image: "traffic.jpg"
      order: 3
    - name: "trafficanalysis"
      endpoint: "https://dashboard.staging.data-wolfsburg.de/d/be4py7rmywow0c/historie-meckauer-weg?orgId=1"
      image: "traffic-analysis.jpg"
      order: 4
    - name: "assetmanagement"
      endpoint: "#/vehicles"
      image: "asset-management.jpg"
      order: 5
    - name: "publicsafety"
      endpoint: "https://cockpit.aic.starwit-infra.de/?continue#/decision/3"
      image: "public-safety.jpg"
      order: 6